### ISSUE TITLE
"purgecss is not a function" error when upgrading gulp-purgecss from 4.0.3 to 4.1.1

### ISSUE THREAD

**Issue by stefanobartoletti** [FullHuman/purgecss#801]
Hi!
I'm getting this error after updating `gulp-purgecss` from version 4.0.3 to 4.1.1:

```
[00:53:05] 'css' errored after 10 ms
[00:53:05] TypeError: purgecss is not a function
    at css (file:///home/runner/work/bricks/bricks/gulpfile.mjs:70:53)
    at bound (domain.js:421:15)
    at runBound (domain.js:432:12)
    at asyncRunner (/home/runner/work/bricks/bricks/node_modules/async-done/index.js:55:18)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
```

This is my gulpfile https://github.com/stefanobartoletti/bricks/blob/devel/gulpfile.mjs, this configuration works before the update but not after.

Is there something that I should modify in my setting, or is this a bug of the plugin itself?

Thanks for your help :)

**Comment by Ffloriel** [comment]
https://github.com/FullHuman/purgecss/issues/800

**Comment by stefanobartoletti** [comment]
Thank you, upgrading to a version superior to 4.1.1 solved the problem
