### ISSUE TITLE
[WebPack Plugin] t.updateAsset is not a function at module.exports.runPluginHook

### ISSUE THREAD

**Issue by mreszke** [FullHuman/purgecss#633]
I'm trying to use the webpack-plugin like in doc(https://purgecss.com/plugins/webpack.html#installation) 
checked on v4.02 and v3.1.3
```
const path = require('path');
const glob = require('glob')
const PurgeCSSPlugin = require('purgecss-webpack-plugin');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');

module.exports = () => {
  ...
  return {
   ...
    module: {
      rules: [
        ...
        {
          test: /\.less$/,
          use: [
            {
              loader: MiniCssExtractPlugin.loader,
              options: {
                publicPath: appConfig.cdn_path
              }
            },
            'css-loader',
            'less-loader'
          ]
        },
        {
          test: /\.css$/,
          use: [
            {
              loader: MiniCssExtractPlugin.loader,
              options: {
                publicPath: appConfig.cdn_path
              }
            },
            'css-loader'
          ]
        }
      ]
    },
    resolve: {
    plugins: [
      ...
      new PurgeCSSPlugin({
        paths: [
          `${projectRootDir}/views/index.ejs`,
          ...glob.sync(`${projectRootDir}/source/**/*`,  { nodir: true })
        ]
      }),
      new MiniCssExtractPlugin({
        filename: useFileHashes ? '[name].[contenthash].css' : '[name].css'
      })
    ]
  };
};
```
But I'm getting error:
```
TypeError: t.updateAsset is not a function
    at module.exports.runPluginHook (/Users/mreszke/Projects/my.livechatinc.com/node_modules/purgecss-webpack-plugin/lib/purgecss-webpack-plugin.js:1:1622)
```

**Comment by Ffloriel** [comment]
Do you have a repo with the issue by any chance?
And which version of webpack are you using?

**Comment by mreszke** [comment]
I don't have a possibility to share this repo.
We are using `webpack@4.29.6` ane you are right, it's working fine with 3.0.0

**Comment by paco3346** [comment]
I had the same problem with `purgecss-webpack-plugin@4.0.2` and `webpack@4.33.0`.

Updated to `webpack@4.46.0` and everything is working as expected.
